# Generated by Django 4.2.6 on 2024-04-29 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='loan_approval',
            new_name='loan_approve',
        ),
    ]
